export const values = {
    'hash': 'Hash', 
    'prev_block': 'Prev Block', 
    'mrkl_root': 'mrkl root', 
    'time': 'Time', 
    'bits': 'Bits', 
    'nonce': 'Nonce', 
    'n_tx': 'n_tx', 
    'size': 'Size',
    'block_index': 'Block Index', 
    'main_chain': 'Main Chain',
    'height': 'Height',
    'received_time': 'Received Time',
    'relayed_by': 'Relayed By',
    'tx': 'tx',
    'message': 'Message',
    'ver': 'Ver',
    vin_sz: 'Vin_sz',
    vout_sz: 'Vout_sz',
    "fee": 'Fee',
    "lock_time": "Lock Time",
    "tx_index": 'T_index',
    "double_spend": 'Double_spend',
    "result": 'Result',
    "balance": 'Balance',
    "block_height": 'Block Height',
    "inputs": 'Inputs',
    "out": 'Out'
}